# Site
name: 'Chinmay'
description: 'Personal thoughts, and learnings.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: ''
email: 'mail[at]chinmaysingh.me'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    chinmay:
      name:           Chinmay
      site:           https://chinmaysingh.me
      avatar:         /assets/images/avatar1.jpg
      bio:            "Developer | Tech Enthusiast | Basketball & History Buff | Networking Hobbyist"
      email:          mail[at]chinmaysingh.me
      twitter:        https://x.com/SinghChinmayy
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
